<?php

namespace ExemploBundle\Repository;

/**
 * MembroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembroRepository extends \Doctrine\ORM\EntityRepository
{
}
