<?php

namespace AppBundle\Repository;

/**
 * TarefaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarefaRepository extends \Doctrine\ORM\EntityRepository
{
}
