<?php

namespace AppBundle\Repository;

/**
 * TarefaStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarefaStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
