app_tarefa:
    resource: "@AppBundle/Controller/TarefaController.php"
    type:     annotation

exemplo:
    resource: "@ExemploBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
